name: Anchorage1770
favicon: null
layout_spectrum: 0.99693
typography_spectrum: 1
title: 'Anchorage 1770 is a boutique waterfront inn located in historic Beaufort, South Carolina'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92befa'
    - '#90918a'
    - '#faf9fe'
    - '#1e1f18'
    - '#545945'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
