name: Anchorage1770
favicon: null
layout_spectrum: 0.99693
typography_spectrum: 0.24642
title: 'Anchorage 1770 is a boutique waterfront inn located in historic Beaufort, South Carolina'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040701'
    - '#ffffff'
    - '#32415e'
    - '#c6a7a9'
    - '#9b552a'
  brandStrength: 0.5
  lightness: 0.20610953425057232
  saturation: 0.0625
  rhythmicContrast: 0.03702485957182944
purpose: []
